"""empty message

Revision ID: 228b34369ad4
Revises: 
Create Date: 2026-04-17 12:45:51.102776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228b34369ad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_surname', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('_forename', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('_dob', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('_country', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('_bio', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_bio')
        batch_op.drop_column('_country')
        batch_op.drop_column('_dob')
        batch_op.drop_column('_forename')
        batch_op.drop_column('_surname')

    # ### end Alembic commands ###
