"""empty message

Revision ID: 8ef8d06e873d
Revises: 228b34369ad4
Create Date: 2026-04-17 12:55:58.930728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef8d06e873d'
down_revision = '228b34369ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('forename', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('country', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('_dob')
        batch_op.drop_column('_surname')
        batch_op.drop_column('_country')
        batch_op.drop_column('_bio')
        batch_op.drop_column('_forename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_forename', sa.BLOB(), nullable=False))
        batch_op.add_column(sa.Column('_bio', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('_country', sa.BLOB(), nullable=False))
        batch_op.add_column(sa.Column('_surname', sa.BLOB(), nullable=False))
        batch_op.add_column(sa.Column('_dob', sa.BLOB(), nullable=False))
        batch_op.drop_column('bio')
        batch_op.drop_column('country')
        batch_op.drop_column('dob')
        batch_op.drop_column('forename')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
